from enum import StrEnum


class ResponseCode(StrEnum):
    # Common
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    BAD_REQUEST = "BAD_REQUEST"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"

    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCESS_TOKEN_NOT_PROVIDED = "ACCESS_TOKEN_NOT_PROVIDED"
    REFRESH_TOKEN_NOT_PROVIDED = "REFRESH_TOKEN_NOT_PROVIDED"
    INVALID_TOKEN_PAYLOAD = "INVALID_TOKEN_PAYLOAD"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_NOT_VALID = "TOKEN_NOT_VALID"
    TOKEN_NOT_VALID_FOR_PROVIDER = "TOKEN_NOT_VALID_FOR_PROVIDER"

    # User management
    DUPLICATE_EMAIL = "DUPLICATE_EMAIL"
    DUPLICATE_USERNAME = "DUPLICATE_USERNAME"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_NOT_ACTIVE = "USER_NOT_ACTIVE"
    USER_NOT_VERIFIED = "USER_NOT_VERIFIED"
